Dropdown
AdelatorreG/JourneysAdmin pull request #20
Opened 2018-08-10 17:41 UTC by davidalvarez93

+Dropdown en el modal añadir y editar Vuelo

2018-08-10 19:58 UTC, ezrra requested changes
Remove the node_modules folder.
Rename variables Spanish to English language.

2018-08-10 19:58 UTC, ezrra commented on database/routes/journeys.routes.js
> +/////////////////////////////////
Remove /////////...

2018-08-10 19:58 UTC, ezrra commented on database/routes/journeys.routes.js
> +//////////////////////////////
Remove /////...

2018-08-10 19:58 UTC, ezrra commented on src/components/AddAirport.js
> +        console.log("modal unmounted");
Remove console.log

2018-08-10 19:58 UTC, ezrra commented on src/components/AddFlights.js
> +
Remove blank line unnecessary

2018-08-10 19:58 UTC, ezrra commented on src/components/AddUser.js
> +        this.AddPermiso=this.AddPermiso.bind(this);
Rename variable and functions to english language

2018-08-10 19:58 UTC, ezrra commented on src/components/AddUser.js
> +            this.fetchPermisos();
Rename variable and functions to english language

2018-08-10 19:58 UTC, ezrra commented on src/components/AddUser.js
> +            <form onSubmit={this.AddPermiso}>
Rename variable and functions to english language

2018-08-10 19:58 UTC, ezrra commented on src/components/AddUser.js
> +                                                <input name="P_Numero" value={this.state.P_Numero} onChange={this.handleChange} type="text" placeholder="Número"/>
Rename variable and functions to english language

2018-08-10 19:58 UTC, ezrra commented on src/components/Airports.js
> +        console.log("modal unmounted");
Remove console.log

2018-08-10 19:58 UTC, ezrra commented on src/components/Flights.js
>          if(window.confirm('Estas seguro de eliminar el aeropuerto')){
Add characters "Signo de interrogación" at question

2018-08-10 19:58 UTC, ezrra commented on src/components/EditFlights.js
> +                            !this.state.Origen ||
Rename variables Spanish to English language

2018-08-10 19:58 UTC, ezrra commented on src/components/Permisos.js
> +const KEYS_TO_FILTERS = ['P_Numero', 'P_UserName', 'P_Date']
Rename variables Spanish to English language

2018-08-10 19:58 UTC, ezrra commented on src/components/Permisos.js
> +            P_Numero:'',
Rename variables Spanish to English language

2018-08-10 19:58 UTC, ezrra commented on src/components/Permisos.js
> +            Permisos:[],
Rename variables Spanish to English language

2018-08-10 19:58 UTC, ezrra commented on src/components/Permisos.js
> +    fetchPermisos(){
Rename variables Spanish to English language

2018-08-10 19:58 UTC, ezrra commented on src/components/Permisos.js
> +        this.fetchPermisos();
Rename variables Spanish to English language

2018-08-17 01:46 UTC, davidalvarez93 commented
+Validación de campos 
-numero
-Fecha
-Hora
+Agregar Usuarios
+Ver Permisos
+Etiquetas de Formularios

2018-08-17 01:47 UTC, merged